[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | migrations
)/
'''

[tool.isort]
profile = "black"
py_version=311
line_length = 120
